-- ================================================================
-- THE FRIEND EXCHANGE
-- Supabase database setup
-- ================================================================
-- Run this entire file once in Supabase → SQL Editor.
-- It creates the tables, security rules, email-account profile
-- trigger, and database functions used by the front end.
-- ================================================================

begin;

-- ----------------------------------------------------------------
-- TABLES
-- ----------------------------------------------------------------

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  balance bigint not null default 1000,
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),

  constraint profiles_display_name_length
    check (char_length(btrim(display_name)) between 2 and 32),
  constraint profiles_balance_nonnegative
    check (balance >= 0)
);

create table if not exists public.markets (
  id bigint generated by default as identity primary key,
  creator_id uuid not null references public.profiles(id) on delete restrict,
  question text not null,
  description text,
  closes_at timestamptz not null,
  status text not null default 'open',
  winning_outcome_id bigint,
  created_at timestamptz not null default now(),
  resolved_at timestamptz,

  constraint markets_question_length
    check (char_length(btrim(question)) between 5 and 180),
  constraint markets_description_length
    check (description is null or char_length(description) <= 600),
  constraint markets_status_valid
    check (status in ('open', 'resolved', 'void'))
);

create table if not exists public.outcomes (
  id bigint generated by default as identity primary key,
  market_id bigint not null references public.markets(id) on delete cascade,
  label text not null,
  sort_order integer not null default 0,
  seed_points bigint not null default 25,
  created_at timestamptz not null default now(),

  constraint outcomes_label_length
    check (char_length(btrim(label)) between 1 and 80),
  constraint outcomes_seed_points_nonnegative
    check (seed_points >= 0),
  constraint outcomes_id_market_unique
    unique (id, market_id)
);

-- Add the market → winning outcome relationship after outcomes exists.
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'markets_winning_outcome_fkey'
      and conrelid = 'public.markets'::regclass
  ) then
    alter table public.markets
      add constraint markets_winning_outcome_fkey
      foreign key (winning_outcome_id)
      references public.outcomes(id)
      on delete restrict;
  end if;
end;
$$;

create table if not exists public.predictions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete restrict,
  market_id bigint not null,
  outcome_id bigint not null,
  amount bigint not null,
  created_at timestamptz not null default now(),

  constraint predictions_amount_positive
    check (amount > 0),
  constraint predictions_outcome_market_fkey
    foreign key (outcome_id, market_id)
    references public.outcomes(id, market_id)
    on delete restrict
);

create table if not exists public.market_payouts (
  market_id bigint not null references public.markets(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete restrict,
  amount bigint not null,
  kind text not null,
  created_at timestamptz not null default now(),

  primary key (market_id, user_id),
  constraint market_payouts_amount_nonnegative
    check (amount >= 0),
  constraint market_payouts_kind_valid
    check (kind in ('winner', 'no_winner_refund', 'void_refund'))
);

create table if not exists public.point_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  market_id bigint references public.markets(id) on delete set null,
  amount bigint not null,
  kind text not null,
  note text,
  created_at timestamptz not null default now(),

  constraint point_transactions_amount_nonzero
    check (amount <> 0),
  constraint point_transactions_kind_valid
    check (kind in ('initial_grant', 'prediction', 'payout', 'refund', 'admin_adjustment'))
);

alter table public.point_transactions
  add column if not exists allowance_period date;

alter table public.point_transactions
  drop constraint if exists point_transactions_kind_valid;

alter table public.point_transactions
  add constraint point_transactions_kind_valid
    check (
      kind in (
        'initial_grant',
        'prediction',
        'payout',
        'refund',
        'admin_adjustment',
        'monthly_allowance'
      )
    );

alter table public.point_transactions
  drop constraint if exists point_transactions_allowance_period_valid;

alter table public.point_transactions
  add constraint point_transactions_allowance_period_valid
    check (
      (
        kind = 'monthly_allowance'
        and allowance_period is not null
        and extract(day from allowance_period) = 1
        and amount = 100
        and market_id is null
      )
      or (
        kind <> 'monthly_allowance'
        and allowance_period is null
      )
    );

-- ----------------------------------------------------------------
-- INDEXES
-- ----------------------------------------------------------------

create index if not exists markets_status_closes_idx
  on public.markets (status, closes_at);

create index if not exists markets_creator_idx
  on public.markets (creator_id);

create index if not exists outcomes_market_idx
  on public.outcomes (market_id, sort_order);

create index if not exists predictions_market_idx
  on public.predictions (market_id, created_at desc);

create index if not exists predictions_user_idx
  on public.predictions (user_id, created_at desc);

create index if not exists predictions_outcome_idx
  on public.predictions (outcome_id);

create index if not exists point_transactions_user_idx
  on public.point_transactions (user_id, created_at desc);

create unique index if not exists point_transactions_monthly_allowance_unique
  on public.point_transactions (user_id, allowance_period)
  where kind = 'monthly_allowance';

-- ----------------------------------------------------------------
-- NEW EMAIL/PASSWORD USER PROFILE TRIGGER
-- ----------------------------------------------------------------

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_display_name text;
begin
  v_display_name := btrim(coalesce(new.raw_user_meta_data ->> 'display_name', ''));

  if char_length(v_display_name) < 2 or char_length(v_display_name) > 32 then
    v_display_name := 'Trader ' || left(new.id::text, 6);
  end if;

  insert into public.profiles (id, display_name, balance)
  values (new.id, v_display_name, 1000)
  on conflict (id) do nothing;

  insert into public.point_transactions (user_id, amount, kind, note)
  values (new.id, 1000, 'initial_grant', 'Welcome grant')
  on conflict do nothing;

  return new;
end;
$$;

-- Recreating the trigger is safe and ensures it points to the current function.
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ----------------------------------------------------------------
-- APP FUNCTIONS
-- All balance-changing actions happen here, inside the database.
-- ----------------------------------------------------------------

create or replace function public.update_display_name(
  p_display_name text
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_name text := btrim(coalesce(p_display_name, ''));
begin
  if v_user_id is null then
    raise exception 'You must be signed in.';
  end if;

  if char_length(v_name) < 2 or char_length(v_name) > 32 then
    raise exception 'Display names must be between 2 and 32 characters.';
  end if;

  update public.profiles
  set display_name = v_name
  where id = v_user_id;

  if not found then
    raise exception 'Profile not found.';
  end if;
end;
$$;

create or replace function public.create_market(
  p_question text,
  p_description text,
  p_closes_at timestamptz,
  p_outcome_labels text[]
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_market_id bigint;
  v_question text := btrim(coalesce(p_question, ''));
  v_description text := nullif(btrim(coalesce(p_description, '')), '');
  v_outcome_count integer;
begin
  if v_user_id is null then
    raise exception 'You must be signed in.';
  end if;

  if char_length(v_question) < 5 or char_length(v_question) > 180 then
    raise exception 'Questions must be between 5 and 180 characters.';
  end if;

  if v_description is not null and char_length(v_description) > 600 then
    raise exception 'Details cannot exceed 600 characters.';
  end if;

  if p_closes_at is null or p_closes_at <= now() then
    raise exception 'The closing time must be in the future.';
  end if;

  v_outcome_count := coalesce(cardinality(p_outcome_labels), 0);
  if v_outcome_count < 2 or v_outcome_count > 10 then
    raise exception 'Markets must have between 2 and 10 outcomes.';
  end if;

  if exists (
    select 1
    from unnest(p_outcome_labels) as item(label)
    where char_length(btrim(coalesce(label, ''))) < 1
       or char_length(btrim(label)) > 80
  ) then
    raise exception 'Each outcome must be between 1 and 80 characters.';
  end if;

  if (
    select count(*) <> count(distinct lower(btrim(label)))
    from unnest(p_outcome_labels) as item(label)
  ) then
    raise exception 'Outcome names must be unique.';
  end if;

  insert into public.markets (
    creator_id,
    question,
    description,
    closes_at
  )
  values (
    v_user_id,
    v_question,
    v_description,
    p_closes_at
  )
  returning id into v_market_id;

  insert into public.outcomes (market_id, label, sort_order, seed_points)
  select
    v_market_id,
    btrim(item.label),
    item.ordinality::integer - 1,
    25
  from unnest(p_outcome_labels) with ordinality as item(label, ordinality);

  return v_market_id;
end;
$$;

create or replace function public.place_prediction(
  p_market_id bigint,
  p_outcome_id bigint,
  p_amount bigint
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_profile public.profiles%rowtype;
  v_market public.markets%rowtype;
  v_outcome_market_id bigint;
  v_prediction_id bigint;
begin
  if v_user_id is null then
    raise exception 'You must be signed in.';
  end if;

  if p_amount is null or p_amount < 1 then
    raise exception 'Prediction amount must be at least 1 point.';
  end if;

  select *
  into v_profile
  from public.profiles
  where id = v_user_id
  for update;

  if not found then
    raise exception 'Profile not found.';
  end if;

  if v_profile.balance < p_amount then
    raise exception 'You do not have enough available points.';
  end if;

  select *
  into v_market
  from public.markets
  where id = p_market_id
  for update;

  if not found then
    raise exception 'Market not found.';
  end if;

  if v_market.status <> 'open' then
    raise exception 'This market is no longer open.';
  end if;

  if now() >= v_market.closes_at then
    raise exception 'Predictions are closed for this market.';
  end if;

  select market_id
  into v_outcome_market_id
  from public.outcomes
  where id = p_outcome_id;

  if not found or v_outcome_market_id <> p_market_id then
    raise exception 'That outcome does not belong to this market.';
  end if;

  update public.profiles
  set balance = balance - p_amount
  where id = v_user_id;

  insert into public.predictions (
    user_id,
    market_id,
    outcome_id,
    amount
  )
  values (
    v_user_id,
    p_market_id,
    p_outcome_id,
    p_amount
  )
  returning id into v_prediction_id;

  insert into public.point_transactions (
    user_id,
    market_id,
    amount,
    kind,
    note
  )
  values (
    v_user_id,
    p_market_id,
    -p_amount,
    'prediction',
    'Prediction placed'
  );

  return v_prediction_id;
end;
$$;

create or replace function public.resolve_market(
  p_market_id bigint,
  p_winning_outcome_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_market public.markets%rowtype;
  v_is_admin boolean := false;
  v_outcome_market_id bigint;
  v_total_pool bigint := 0;
  v_winning_pool bigint := 0;
  v_payout_total bigint := 0;
begin
  if v_user_id is null then
    raise exception 'You must be signed in.';
  end if;

  select coalesce(is_admin, false)
  into v_is_admin
  from public.profiles
  where id = v_user_id;

  select *
  into v_market
  from public.markets
  where id = p_market_id
  for update;

  if not found then
    raise exception 'Market not found.';
  end if;

  if v_market.creator_id <> v_user_id and not v_is_admin then
    raise exception 'Only the market creator or an administrator can resolve this market.';
  end if;

  if v_market.status <> 'open' then
    raise exception 'This market has already been resolved or voided.';
  end if;

  if now() < v_market.closes_at and not v_is_admin then
    raise exception 'The market cannot be resolved before its closing time.';
  end if;

  select market_id
  into v_outcome_market_id
  from public.outcomes
  where id = p_winning_outcome_id;

  if not found or v_outcome_market_id <> p_market_id then
    raise exception 'That outcome does not belong to this market.';
  end if;

  select coalesce(sum(amount), 0)
  into v_total_pool
  from public.predictions
  where market_id = p_market_id;

  select coalesce(sum(amount), 0)
  into v_winning_pool
  from public.predictions
  where market_id = p_market_id
    and outcome_id = p_winning_outcome_id;

  -- Nobody predicted anything: resolve cleanly with no payouts.
  if v_total_pool = 0 then
    update public.markets
    set
      status = 'resolved',
      winning_outcome_id = p_winning_outcome_id,
      resolved_at = now()
    where id = p_market_id;

    return jsonb_build_object(
      'market_id', p_market_id,
      'total_pool', 0,
      'winning_pool', 0,
      'payout_total', 0,
      'refunded', false
    );
  end if;

  -- If nobody backed the real winner, refund every participant.
  if v_winning_pool = 0 then
    insert into public.market_payouts (market_id, user_id, amount, kind)
    select
      p_market_id,
      user_id,
      sum(amount)::bigint,
      'no_winner_refund'
    from public.predictions
    where market_id = p_market_id
    group by user_id;

    update public.profiles as profile
    set balance = profile.balance + payout.amount
    from public.market_payouts as payout
    where payout.market_id = p_market_id
      and payout.user_id = profile.id;

    insert into public.point_transactions (
      user_id,
      market_id,
      amount,
      kind,
      note
    )
    select
      user_id,
      market_id,
      amount,
      'refund',
      'Refunded because nobody selected the winning outcome'
    from public.market_payouts
    where market_id = p_market_id;

    update public.markets
    set
      status = 'resolved',
      winning_outcome_id = p_winning_outcome_id,
      resolved_at = now()
    where id = p_market_id;

    return jsonb_build_object(
      'market_id', p_market_id,
      'total_pool', v_total_pool,
      'winning_pool', 0,
      'payout_total', v_total_pool,
      'refunded', true
    );
  end if;

  -- Distribute the entire pool among winning users in proportion to stake.
  -- Integer rounding leftovers are assigned by largest fractional remainder,
  -- ensuring that the full pool is distributed exactly.
  with stakes as (
    select
      user_id,
      sum(amount)::bigint as stake
    from public.predictions
    where market_id = p_market_id
      and outcome_id = p_winning_outcome_id
    group by user_id
  ),
  raw_payouts as (
    select
      user_id,
      stake,
      (stake::numeric * v_total_pool::numeric / v_winning_pool::numeric) as exact_payout
    from stakes
  ),
  rounded as (
    select
      user_id,
      floor(exact_payout)::bigint as base_payout,
      exact_payout - floor(exact_payout) as fractional_remainder
    from raw_payouts
  ),
  ranked as (
    select
      user_id,
      base_payout,
      row_number() over (order by fractional_remainder desc, user_id) as remainder_rank,
      (v_total_pool - sum(base_payout) over ())::bigint as leftover_points
    from rounded
  )
  insert into public.market_payouts (market_id, user_id, amount, kind)
  select
    p_market_id,
    user_id,
    base_payout + case when remainder_rank <= leftover_points then 1 else 0 end,
    'winner'
  from ranked;

  update public.profiles as profile
  set balance = profile.balance + payout.amount
  from public.market_payouts as payout
  where payout.market_id = p_market_id
    and payout.user_id = profile.id;

  insert into public.point_transactions (
    user_id,
    market_id,
    amount,
    kind,
    note
  )
  select
    user_id,
    market_id,
    amount,
    'payout',
    'Winning market payout'
  from public.market_payouts
  where market_id = p_market_id;

  select coalesce(sum(amount), 0)
  into v_payout_total
  from public.market_payouts
  where market_id = p_market_id;

  if v_payout_total <> v_total_pool then
    raise exception 'Payout calculation failed to distribute the full pool.';
  end if;

  update public.markets
  set
    status = 'resolved',
    winning_outcome_id = p_winning_outcome_id,
    resolved_at = now()
  where id = p_market_id;

  return jsonb_build_object(
    'market_id', p_market_id,
    'total_pool', v_total_pool,
    'winning_pool', v_winning_pool,
    'payout_total', v_payout_total,
    'refunded', false
  );
end;
$$;

create or replace function public.void_market(
  p_market_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_market public.markets%rowtype;
  v_is_admin boolean := false;
  v_refund_total bigint := 0;
begin
  if v_user_id is null then
    raise exception 'You must be signed in.';
  end if;

  select coalesce(is_admin, false)
  into v_is_admin
  from public.profiles
  where id = v_user_id;

  select *
  into v_market
  from public.markets
  where id = p_market_id
  for update;

  if not found then
    raise exception 'Market not found.';
  end if;

  if v_market.creator_id <> v_user_id and not v_is_admin then
    raise exception 'Only the market creator or an administrator can void this market.';
  end if;

  if v_market.status <> 'open' then
    raise exception 'This market has already been resolved or voided.';
  end if;

  insert into public.market_payouts (market_id, user_id, amount, kind)
  select
    p_market_id,
    user_id,
    sum(amount)::bigint,
    'void_refund'
  from public.predictions
  where market_id = p_market_id
  group by user_id;

  update public.profiles as profile
  set balance = profile.balance + payout.amount
  from public.market_payouts as payout
  where payout.market_id = p_market_id
    and payout.user_id = profile.id;

  insert into public.point_transactions (
    user_id,
    market_id,
    amount,
    kind,
    note
  )
  select
    user_id,
    market_id,
    amount,
    'refund',
    'Market voided and refunded'
  from public.market_payouts
  where market_id = p_market_id;

  select coalesce(sum(amount), 0)
  into v_refund_total
  from public.market_payouts
  where market_id = p_market_id;

  update public.markets
  set
    status = 'void',
    winning_outcome_id = null,
    resolved_at = now()
  where id = p_market_id;

  return jsonb_build_object(
    'market_id', p_market_id,
    'refund_total', v_refund_total
  );
end;
$$;

create or replace function public.award_points(
  p_user_id uuid,
  p_amount bigint,
  p_note text default 'Manual admin adjustment'
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_admin_id uuid := auth.uid();
  v_is_admin boolean := false;
  v_current_balance bigint;
  v_new_balance bigint;
begin
  if v_admin_id is null then
    raise exception 'You must be signed in.';
  end if;

  select coalesce(is_admin, false)
  into v_is_admin
  from public.profiles
  where id = v_admin_id;

  if not v_is_admin then
    raise exception 'Only administrators can adjust point balances.';
  end if;

  if p_amount is null or p_amount = 0 then
    raise exception 'The adjustment must be a non-zero number of points.';
  end if;

  select balance
  into v_current_balance
  from public.profiles
  where id = p_user_id
  for update;

  if not found then
    raise exception 'Target profile not found.';
  end if;

  v_new_balance := v_current_balance + p_amount;
  if v_new_balance < 0 then
    raise exception 'This adjustment would make the balance negative.';
  end if;

  update public.profiles
  set balance = v_new_balance
  where id = p_user_id;

  insert into public.point_transactions (
    user_id,
    amount,
    kind,
    note
  )
  values (
    p_user_id,
    p_amount,
    'admin_adjustment',
    left(coalesce(nullif(btrim(p_note), ''), 'Manual admin adjustment'), 200)
  );

  return v_new_balance;
end;
$$;

create or replace function public.grant_monthly_allowance(
  p_allowance_period date default (
    date_trunc('month', timezone('America/Chicago', now()))::date
  )
)
returns table (
  grant_period date,
  recipient_count bigint,
  points_granted bigint
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_period_start timestamp with time zone;
begin
  if p_allowance_period is null
     or extract(day from p_allowance_period) <> 1 then
    raise exception 'Allowance period must be the first day of a month.';
  end if;

  v_period_start :=
    p_allowance_period::timestamp at time zone 'America/Chicago';

  return query
  with eligible_accounts as (
    select profile.id
    from public.profiles as profile
    join auth.users as auth_user
      on auth_user.id = profile.id
    where auth_user.last_sign_in_at >= v_period_start - interval '90 days'
      and auth_user.last_sign_in_at <= now()
  ),
  new_allowances as (
    insert into public.point_transactions (
      user_id,
      amount,
      kind,
      note,
      allowance_period
    )
    select
      eligible.id,
      100,
      'monthly_allowance',
      'Monthly active-trader allowance',
      p_allowance_period
    from eligible_accounts as eligible
    on conflict (user_id, allowance_period)
      where kind = 'monthly_allowance'
      do nothing
    returning user_id, amount
  ),
  credited_accounts as (
    update public.profiles as profile
    set balance = profile.balance + allowance.amount
    from new_allowances as allowance
    where profile.id = allowance.user_id
    returning allowance.amount
  )
  select
    p_allowance_period,
    count(*)::bigint,
    coalesce(sum(credited.amount), 0)::bigint
  from credited_accounts as credited;
end;
$$;

-- ----------------------------------------------------------------
-- ROW LEVEL SECURITY
-- Users may read community data. All writes go through the functions
-- above so browsers cannot directly edit balances, outcomes, or results.
-- ----------------------------------------------------------------

alter table public.profiles enable row level security;
alter table public.markets enable row level security;
alter table public.outcomes enable row level security;
alter table public.predictions enable row level security;
alter table public.market_payouts enable row level security;
alter table public.point_transactions enable row level security;

-- Remove broad table-writing privileges from browser roles.
revoke all on table public.profiles from anon, authenticated;
revoke all on table public.markets from anon, authenticated;
revoke all on table public.outcomes from anon, authenticated;
revoke all on table public.predictions from anon, authenticated;
revoke all on table public.market_payouts from anon, authenticated;
revoke all on table public.point_transactions from anon, authenticated;

-- Authenticated users may read the public exchange data.
grant select on table public.profiles to authenticated;
grant select on table public.markets to authenticated;
grant select on table public.outcomes to authenticated;
grant select on table public.predictions to authenticated;
grant select on table public.market_payouts to authenticated;
grant select on table public.point_transactions to authenticated;

-- The identity sequences remain inaccessible because inserts happen in
-- security-definer functions, not directly from the browser.

-- Recreate policies so this file can be re-run safely.
drop policy if exists "Authenticated users can read profiles" on public.profiles;
create policy "Authenticated users can read profiles"
on public.profiles
for select
to authenticated
using (true);

drop policy if exists "Authenticated users can read markets" on public.markets;
create policy "Authenticated users can read markets"
on public.markets
for select
to authenticated
using (true);

drop policy if exists "Authenticated users can read outcomes" on public.outcomes;
create policy "Authenticated users can read outcomes"
on public.outcomes
for select
to authenticated
using (true);

drop policy if exists "Authenticated users can read predictions" on public.predictions;
create policy "Authenticated users can read predictions"
on public.predictions
for select
to authenticated
using (true);

drop policy if exists "Authenticated users can read payouts" on public.market_payouts;
create policy "Authenticated users can read payouts"
on public.market_payouts
for select
to authenticated
using (true);

drop policy if exists "Users can read their own transactions and admins can read all" on public.point_transactions;
create policy "Users can read their own transactions and admins can read all"
on public.point_transactions
for select
to authenticated
using (
  user_id = (select auth.uid())
  or exists (
    select 1
    from public.profiles
    where id = (select auth.uid())
      and is_admin = true
  )
);

-- Function execution permissions.
revoke all on function public.update_display_name(text) from public, anon;
revoke all on function public.create_market(text, text, timestamptz, text[]) from public, anon;
revoke all on function public.place_prediction(bigint, bigint, bigint) from public, anon;
revoke all on function public.resolve_market(bigint, bigint) from public, anon;
revoke all on function public.void_market(bigint) from public, anon;
revoke all on function public.award_points(uuid, bigint, text) from public, anon;
revoke all on function public.grant_monthly_allowance(date) from public, anon, authenticated;

grant execute on function public.update_display_name(text) to authenticated;
grant execute on function public.create_market(text, text, timestamptz, text[]) to authenticated;
grant execute on function public.place_prediction(bigint, bigint, bigint) to authenticated;
grant execute on function public.resolve_market(bigint, bigint) to authenticated;
grant execute on function public.void_market(bigint) to authenticated;
grant execute on function public.award_points(uuid, bigint, text) to authenticated;

commit;

-- ----------------------------------------------------------------
-- MONTHLY ACTIVE-TRADER ALLOWANCE
-- 06:05 UTC is 00:05 CST / 01:05 CDT on the first day of the month.
-- Reusing this job name safely updates the existing schedule.
-- ----------------------------------------------------------------

create extension if not exists pg_cron;

select cron.schedule(
  'friend-exchange-monthly-allowance',
  '5 6 1 * *',
  'select public.grant_monthly_allowance();'
);

-- ----------------------------------------------------------------
-- OPTIONAL REALTIME SETUP
-- This makes open pages refresh automatically when friends act.
-- The block is safe to run again and skips tables already published.
-- ----------------------------------------------------------------

do $$
declare
  v_table text;
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    foreach v_table in array array[
      'profiles',
      'markets',
      'outcomes',
      'predictions',
      'market_payouts'
    ]
    loop
      if not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = v_table
      ) then
        execute format('alter publication supabase_realtime add table public.%I', v_table);
      end if;
    end loop;
  end if;
end;
$$;

-- ================================================================
-- AFTER YOUR FIRST SIGN-IN
-- ================================================================
-- To make yourself the administrator, create your account once, then
-- run this query with your login email:
--
-- update public.profiles as profile
-- set is_admin = true
-- from auth.users as auth_user
-- where profile.id = auth_user.id
--   and lower(auth_user.email) = lower('you@example.com');
--
-- The admin can resolve any market early, void any open market, and
-- award or deduct points from the leaderboard/account screen.
-- ================================================================
